services:
  app:
    build: .
    platform: linux/amd64
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_DATABASE=laravel_11_learning"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_11_learning
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  webserver:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # # MailHog (для тестирования email)
  # mailhog:
  #   image: mailhog/mailhog
  #   container_name: mailhog
  #   ports:
  #     - "1025:1025"   # SMTP
  #     - "8025:8025"   # Web UI

volumes:
  mysql_data: