services:
  app:
    platform: linux/amd64
    image: php:8.3-fpm-alpine
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - "DB_HOST=127.0.0.1"
      - "DB_PORT=3306"
      - "DB_DATABASE=laravel_11_learning"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
    depends_on:
      - db
    command: sh -c "docker-php-ext-install pdo_mysql"

  # MySQL 8.0
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_11_learning
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Nginx
  webserver:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # # MailHog (для тестирования email)
  # mailhog:
  #   image: mailhog/mailhog
  #   container_name: mailhog
  #   ports:
  #     - "1025:1025"   # SMTP
  #     - "8025:8025"   # Web UI

volumes:
  mysql_data: